<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">测试报告</h1>
<p class='attribute'><strong>测试人员 : </strong> JM</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-12-31 11:01:04</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:16.823000</p>
<p class='attribute'><strong>测试结果 : </strong> 共 33，通过 1，错误 32，通过率= 3.03%</p>

<p class='description'>测试用</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 3.03% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 0 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 1 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 33 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='errorClass warning'>
    <td>test_case.test_case_sit.TestHttp01</td>
    <td class="text-center">33</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">32</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',33)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_01</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse in" align="left">
    <pre>
    
ft1_1: ----------------------------------------
测试场景：限时权限分享_正常分享_资源拥有者分享(user_owner登陆)[200]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用成功: &lt;Response [200]&gt;
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_02</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse in" align="left">
    <pre>
    
ft1_2: ----------------------------------------
测试场景：限时权限分享_正常分享_资源分享者分享(user_share登陆)[200]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用成功: &lt;Response [200]&gt;
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_03</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: ----------------------------------------
测试场景：限时权限分享_有效校验_authSpace不存在[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key0_authSpace001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': '权限空间[key0_authSpace001]不存在', 'utCode': 1209, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_04</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: ----------------------------------------
测试场景：限时权限分享_有效校验_resourceKey不存在[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey0_002', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': '资源不存在！', 'utCode': 1205, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_05</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse in" align="left">
    <pre>
    
ft1_5: ----------------------------------------
测试场景：限时权限分享_有效校验_authId不存在[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': 'authId000', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': '权限ID不存在！', 'utCode': 1208, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_06</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse in" align="left">
    <pre>
    
ft1_6: ----------------------------------------
测试场景：限时权限分享_有效校验_使用限时、循环授权ID[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348388', 'userKey': 'user_used01_01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': '该授权ID不属于当前用户！', 'utCode': 1409, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_07</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse in" align="left">
    <pre>
    
ft1_7: ----------------------------------------
测试场景：限时权限分享_有效校验_userKey分享给自己[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_share', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': '权限不允许分享给自己！', 'utCode': 1302, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_08</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>错误</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>错误</button>
    <div id='div_ft1_8' class="collapse in" align="left">
    <pre>
    
ft1_8: ----------------------------------------
测试场景：限时权限分享_有效校验_不同userKey[200]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_02', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用成功: &lt;Response [200]&gt;
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_9' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_09</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_9'>错误</button>
    <div id='div_ft1_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_9'>错误</button>
    <div id='div_ft1_9' class="collapse in" align="left">
    <pre>
    
ft1_9: ----------------------------------------
测试场景：限时权限分享_有效校验_userKey分享给资源拥有者[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_owner', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': '不能分享给资源拥有者！', 'utCode': 1405, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_10' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_10</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_10'>错误</button>
    <div id='div_ft1_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_10'>错误</button>
    <div id='div_ft1_10' class="collapse in" align="left">
    <pre>
    
ft1_10: ----------------------------------------
测试场景：限时权限分享_有效校验_userKey分享给开发者（资源创建者）[200]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'jiangman', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用成功: &lt;Response [200]&gt;
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_11' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_11</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_11'>错误</button>
    <div id='div_ft1_11' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_11'>错误</button>
    <div id='div_ft1_11' class="collapse in" align="left">
    <pre>
    
ft1_11: ----------------------------------------
测试场景：限时权限分享_有效校验_userKey分享给开发者（非资源创建者）[200]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'platform_admin', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用成功: &lt;Response [200]&gt;
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_12' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_12</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_12'>错误</button>
    <div id='div_ft1_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_12'>错误</button>
    <div id='div_ft1_12' class="collapse in" align="left">
    <pre>
    
ft1_12: ----------------------------------------
测试场景：限时权限分享_有效校验_userKey已享有永久权限[200]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_share01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用成功: &lt;Response [200]&gt;
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_13' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_13</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_13'>错误</button>
    <div id='div_ft1_13' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_13'>错误</button>
    <div id='div_ft1_13' class="collapse in" align="left">
    <pre>
    
ft1_13: ----------------------------------------
测试场景：限时权限分享_有效校验_相同userKey再次分享[200]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用成功: &lt;Response [200]&gt;
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_14' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_14</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_14'>错误</button>
    <div id='div_ft1_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_14'>错误</button>
    <div id='div_ft1_14' class="collapse in" align="left">
    <pre>
    
ft1_14: ----------------------------------------
测试场景：限时权限分享_有效校验_用户无资源分享权限（无资源功能使用权限）[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_002', 'authId': '3857593974336348194', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': '权限ID不存在！', 'utCode': 1208, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_15' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_15</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_15'>错误</button>
    <div id='div_ft1_15' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_15'>错误</button>
    <div id='div_ft1_15' class="collapse in" align="left">
    <pre>
    
ft1_15: ----------------------------------------
测试场景：限时权限分享_有效校验_用户无资源分享权限（有资源功能使用权限，无authId使用权限）[200]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348385', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': '该授权ID不属于当前用户！', 'utCode': 1409, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_16' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_16</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_16'>错误</button>
    <div id='div_ft1_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_16'>错误</button>
    <div id='div_ft1_16' class="collapse in" align="left">
    <pre>
    
ft1_16: ----------------------------------------
测试场景：限时权限分享_有效校验_已解绑资源[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_005', 'authId': '3857593974336348402', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用成功: &lt;Response [200]&gt;
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_17' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_17</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_17' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_17'>错误</button>
    <div id='div_ft1_17' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_17' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_17'>错误</button>
    <div id='div_ft1_17' class="collapse in" align="left">
    <pre>
    
ft1_17: ----------------------------------------
测试场景：限时权限分享_有效校验_startDateTime&gt;endDateTime[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2020-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': '开始时间不能大于结束时间！', 'utCode': 1503, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_18' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_18</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_18' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_18'>错误</button>
    <div id='div_ft1_18' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_18' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_18'>错误</button>
    <div id='div_ft1_18' class="collapse in" align="left">
    <pre>
    
ft1_18: ----------------------------------------
测试场景：限时权限分享_有效校验_startDateTime=endDateTime[200]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2020-12-01 10:35', 'endDateTime': '2020-12-01 10:35', 'count': 10}
接口调用成功: &lt;Response [200]&gt;
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_19' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_19</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_19' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_19'>错误</button>
    <div id='div_ft1_19' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_19' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_19'>错误</button>
    <div id='div_ft1_19' class="collapse in" align="left">
    <pre>
    
ft1_19: ----------------------------------------
测试场景：限时权限分享_有效校验_endDateTime&lt;当前时间[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2018-12-01 10:35', 'endDateTime': '2018-12-01 10:35', 'count': 10}
接口调用失败:{'utMsg': '结束时间需要大于当前时间！', 'utCode': 1504, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_20' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_20</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_20' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_20'>错误</button>
    <div id='div_ft1_20' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_20' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_20'>错误</button>
    <div id='div_ft1_20' class="collapse in" align="left">
    <pre>
    
ft1_20: ----------------------------------------
测试场景：限时权限分享_必填校验_authSpace为空[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': '', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': 'authSpace:权限空间标识不能为空; ', 'utCode': 1202, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_21' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_21</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_21' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_21'>错误</button>
    <div id='div_ft1_21' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_21' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_21'>错误</button>
    <div id='div_ft1_21' class="collapse in" align="left">
    <pre>
    
ft1_21: ----------------------------------------
测试场景：限时权限分享_必填校验_resourceKey为空[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': '', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': 'resourceKey:资源唯一标识不能为空; ', 'utCode': 1202, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_22' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_22</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_22' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_22'>错误</button>
    <div id='div_ft1_22' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_22' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_22'>错误</button>
    <div id='div_ft1_22' class="collapse in" align="left">
    <pre>
    
ft1_22: ----------------------------------------
测试场景：限时权限分享_必填校验_authId为空[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': 'authId:权限分享ID不能为空; ', 'utCode': 1202, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_23' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_23</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_23' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_23'>错误</button>
    <div id='div_ft1_23' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_23' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_23'>错误</button>
    <div id='div_ft1_23' class="collapse in" align="left">
    <pre>
    
ft1_23: ----------------------------------------
测试场景：限时权限分享_必填校验_userKey为空[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': '', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': 'userKey:用户唯一标识不能为空; ', 'utCode': 1202, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_24' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_24</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_24' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_24'>错误</button>
    <div id='div_ft1_24' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_24' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_24'>错误</button>
    <div id='div_ft1_24' class="collapse in" align="left">
    <pre>
    
ft1_24: ----------------------------------------
测试场景：限时权限分享_必填校验_startDateTime为空[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '', 'endDateTime': '2020-01-20 10:35', 'count': 10}
接口调用失败:{'utMsg': 'startDateTime:起始时间不能为空; ', 'utCode': 1202, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_25' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_25</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_25' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_25'>错误</button>
    <div id='div_ft1_25' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_25' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_25'>错误</button>
    <div id='div_ft1_25' class="collapse in" align="left">
    <pre>
    
ft1_25: ----------------------------------------
测试场景：限时权限分享_必填校验_endDateTime为空[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '', 'count': 10}
接口调用失败:{'utMsg': 'endDateTime:结束时间不能为空; ', 'utCode': 1202, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_26' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_26</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_26' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_26'>错误</button>
    <div id='div_ft1_26' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_26' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_26'>错误</button>
    <div id='div_ft1_26' class="collapse in" align="left">
    <pre>
    
ft1_26: ----------------------------------------
测试场景：限时权限分享_必填校验_count为空[200]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-01-20 10:35', 'count': ''}
接口调用成功: &lt;Response [200]&gt;
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_27' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_27</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_27' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_27'>错误</button>
    <div id='div_ft1_27' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_27' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_27'>错误</button>
    <div id='div_ft1_27' class="collapse in" align="left">
    <pre>
    
ft1_27: ----------------------------------------
测试场景：限时权限分享_格式校验_startDateTime格式有误_非time[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '二零一九年', 'endDateTime': '2020-12-01 10:35', 'count': 10}
接口调用失败:{'utMsg': '时间格式有误 yyyy-MM-dd HH:mm ,请重新输入！', 'utCode': 1108, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_28' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_28</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_28' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_28'>错误</button>
    <div id='div_ft1_28' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_28' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_28'>错误</button>
    <div id='div_ft1_28' class="collapse in" align="left">
    <pre>
    
ft1_28: ----------------------------------------
测试场景：限时权限分享_格式校验_startDateTime格式有误_time格式不支持[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '20191201 10:35', 'endDateTime': '2020-12-01 10:35', 'count': 10}
接口调用失败:{'utMsg': '时间格式有误 yyyy-MM-dd HH:mm ,请重新输入！', 'utCode': 1108, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_29' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_29</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_29' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_29'>错误</button>
    <div id='div_ft1_29' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_29' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_29'>错误</button>
    <div id='div_ft1_29' class="collapse in" align="left">
    <pre>
    
ft1_29: ----------------------------------------
测试场景：限时权限分享_格式校验_startDateTime格式有误_时间有误[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-13-39 28:89', 'endDateTime': '2020-12-01 10:35', 'count': 10}
接口调用失败:{'utMsg': '时间格式有误 yyyy-MM-dd HH:mm ,请重新输入！', 'utCode': 1108, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_30' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_30</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_30' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_30'>错误</button>
    <div id='div_ft1_30' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_30' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_30'>错误</button>
    <div id='div_ft1_30' class="collapse in" align="left">
    <pre>
    
ft1_30: ----------------------------------------
测试场景：限时权限分享_格式校验_endDateTime格式有误[500]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '2020-12-01 26:35', 'count': 10}
接口调用失败:{'utMsg': '时间格式有误 yyyy-MM-dd HH:mm ,请重新输入！', 'utCode': 1108, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_31' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_31</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_31' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_31'>错误</button>
    <div id='div_ft1_31' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_31' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_31'>错误</button>
    <div id='div_ft1_31' class="collapse in" align="left">
    <pre>
    
ft1_31: ----------------------------------------
测试场景：限时权限分享_格式校验_count格式有误[400]
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{'authSpace': 'key_authSpace200_001', 'resourceKey': 'ResourceKey200_001', 'authId': '3857593974336348381', 'userKey': 'user_used01', 'startDateTime': '2019-12-01 10:35', 'endDateTime': '', 'count': 'one'}
接口调用失败:{'timestamp': 1577761225282, 'status': 400, 'error': 'Bad Request', 'message': 'Bad Request', 'path': '/authorize/timeLimitedShare'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_32' class='none'>
    <td class='errorCase'><div class='testcase'>test_001_32</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_32' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_32'>错误</button>
    <div id='div_ft1_32' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_32' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_32'>错误</button>
    <div id='div_ft1_32' class="collapse in" align="left">
    <pre>
    
ft1_32: ----------------------------------------
测试场景：限时权限分享_格式、边界校验
调用的地址是:https://mobileuat.utcook.com//auth-internet/authorize/timeLimitedShare
请求参数:{}
接口调用失败:{'utMsg': 'endDateTime:结束时间不能为空; authId:权限分享ID不能为空; userKey:用户唯一标识不能为空; resourceKey:资源唯一标识不能为空; authSpace:权限空间标识不能为空; startDateTime:起始时间不能为空; ', 'utCode': 1202, 'utService': 'auth-internet-service'}:
----------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "E:\jiangman\newtest\test_authority\test_case\test_case_sit.py", line 41, in test_001
    do_excel().into_date(num + 1, (do_excel().max_column + 1), res.status_code)
  File "E:\jiangman\newtest\test_authority\common\do_excel.py", line 35, in into_date
    self.wb.save(get_common().get_excel()[0])#保存excel
  File "D:\Program Files\python\lib\site-packages\openpyxl\workbook\workbook.py", line 408, in save
    save_workbook(self, filename)
  File "D:\Program Files\python\lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "D:\Program Files\python\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'E:\\jiangman\\newtest\\test_authority\\test_data\\word.xlsx'


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_33' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_002</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_33' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_33'>通过</button>
    <div id='div_pt1_33' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_33' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_33'>通过</button>
    <div id='div_pt1_33' class="collapse in" align="left">
    <pre>
    
pt1_33: ----------------------------------------
----------------------------------------


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>33</td>
    <td>1</td>
    <td>0</td>
    <td>32</td>
    <td>通过率：3.03%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
